// auto-generated by scripts/gen-env.ts; DO NOT EDIT
// Synced from third_party/QuickJS headers at build time
export const FIRST_ATOM = 228 // quickjs-atom.h DEF count + 1
export const BC_VERSION = 5
