import { QuickJSLib } from './QuickJSLib'
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

async function main() {
  const envPath = resolve(process.cwd(), 'src/env.ts')
  
  const compileFlags = await QuickJSLib.getCompileEnums()
  const bytecodeTags = await QuickJSLib.getAllBytecodeTags()
  const functionKinds = await QuickJSLib.getFunctionKinds()
  const jsModes = await QuickJSLib.getJSModes()
  const pc2LineCodes = await QuickJSLib.getPC2LineCodes()
  const opFormats = await QuickJSLib.getAllOpcodeFormats()
  const opcodes = await QuickJSLib.getAllOpcodes()
  const atoms = await QuickJSLib.getAllAtoms()
  const envAtoms = await QuickJSLib.getEnvironmentAtoms()
  writeFileSync('env_atoms.json', JSON.stringify(envAtoms, null, 2))
  const bytecodeVersion = await QuickJSLib.getBytecodeVersion()
  const compileOptions = await QuickJSLib.getCompileOptions()
  const firstAtomId = await QuickJSLib.getFirstAtomId()

  const lines: string[] = []
  lines.push(`// This file is auto-generated by scripts/getEnv.ts`)
  lines.push(`// Do not edit manually.`)
  lines.push(`// Generated at: ${new Date().toISOString()}`)
  lines.push(``)

  // CompileFlags
  lines.push(`export enum CompileFlags {`)
  for (const [key, value] of Object.entries(compileFlags)) {
    lines.push(`  ${key} = ${value},`)
  }
  lines.push(`}`)
  lines.push(``)

  // BytecodeTag
  lines.push(`export enum BytecodeTag {`)
  for (const [key, value] of Object.entries(bytecodeTags)) {
    lines.push(`  ${key} = ${value},`)
  }
  lines.push(`}`)
  lines.push(``)

  // FunctionKind
  lines.push(`export enum FunctionKind {`)
  for (const [key, value] of Object.entries(functionKinds)) {
    lines.push(`  ${key} = ${value},`)
  }
  lines.push(`}`)
  lines.push(``)

  // JSMode
  lines.push(`export enum JSMode {`)
  for (const [key, value] of Object.entries(jsModes)) {
    lines.push(`  ${key} = ${value},`)
  }
  lines.push(`}`)
  lines.push(``)

  // PC2Line
  lines.push(`export enum PC2Line {`)
  for (const [key, value] of Object.entries(pc2LineCodes)) {
    lines.push(`  ${key} = ${value},`)
  }
  lines.push(`}`)
  lines.push(``)

  // OpFormat
  lines.push(`export enum OpFormat {`)
  for (const [key, value] of Object.entries(opFormats)) {
    lines.push(`  ${key} = ${value},`)
  }
  lines.push(`}`)
  lines.push(``)

  // Opcode Enum
  lines.push(`export enum Opcode {`)
  for (const op of opcodes) {
    lines.push(`  OP_${op.name} = ${op.code},`)
  }
  lines.push(`}`)
  lines.push(``)

  // OPCODE_NAME_TO_CODE
  lines.push(`export const OPCODE_NAME_TO_CODE: Record<string, number> = {`)
  for (const op of opcodes) {
    lines.push(`  "${op.name}": ${op.code},`)
  }
  lines.push(`}`)
  lines.push(``)

  // JSAtom Enum (Static Atoms)
  lines.push(`export enum JSAtom {`)
  const atomEnumNames = new Map<number, string>()
  const atomStrings = new Map<number, string>()

  for (const atom of atoms) {
    // For Enum: use the first name seen for an ID (which is the identifier)
    if (!atomEnumNames.has(atom.id)) {
      atomEnumNames.set(atom.id, atom.key)
    }
    // For Strings: use the last name seen for an ID (which is the string value)
    atomStrings.set(atom.id, atom.key)
  }

  for (const [id, key] of atomEnumNames) {
    if (key === 'empty_string') {
      lines.push(`  JS_ATOM_empty_string = ${id},`)
    } else if (key === '<private_brand>') {
      lines.push(`  JS_ATOM_Private_brand = ${id},`)
    } else {
      lines.push(`  JS_ATOM_${key} = ${id},`)
    }
  }
  lines.push(`}`)
  lines.push(``)

  // ATOM_STRINGS (Static Atoms)
  lines.push(`export const ATOM_STRINGS: Record<number, string> = {`)
  for (const [id, key] of atomStrings) {
    if (key === 'empty_string') {
      lines.push(`  ${id}: "",`)
    } else if (key === '<private_brand>') {
      lines.push(`  ${id}: "Private_brand",`)
    } else {
      lines.push(`  ${id}: "${key}",`)
    }
  }
  lines.push(`}`)
  lines.push(``)

  // OpcodeDefinition
  lines.push(`export interface OpcodeDefinition {`)
  lines.push(`  id: string`)
  lines.push(`  size: number`)
  lines.push(`  nPop: number`)
  lines.push(`  nPush: number`)
  lines.push(`  format: OpFormat`)
  lines.push(`}`)
  lines.push(``)

  // OPCODE_DEFS
  lines.push(`export const OPCODE_DEFS: Record<string, OpcodeDefinition> = {`)
  const fmtMap = new Map(Object.entries(opFormats).map(([k, v]) => [v, k]))
  for (const op of opcodes) {
    const fmtName = fmtMap.get(op.fmt) || 'none'
    lines.push(`  OP_${op.name}: { id: "${op.name}", size: ${op.size}, nPop: ${op.nPop}, nPush: ${op.nPush}, format: OpFormat.${fmtName} },`)
  }
  lines.push(`}`)
  lines.push(``)

  // SHORT_OPCODE_DEFS
  lines.push(`export const SHORT_OPCODE_DEFS: Record<string, OpcodeDefinition> = {`)
  // Assuming short opcodes are those with size < 5 or specific range?
  // Actually, the C++ code defines SHORT_OPCODES.
  // But here we can just dump all of them or filter if we knew which are short.
  // The previous file had a subset.
  // For now, let's just dump the same set as OPCODE_DEFS but maybe filtered?
  // The previous file had a specific list.
  // Let's just replicate OPCODE_DEFS for now, or maybe we can detect short opcodes?
  // In QuickJS, short opcodes are aliases.
  // But getOpcodes returns all of them.
  // Let's just use the same list for now, or maybe filter by name?
  // The previous list seemed to be a subset.
  // Let's just include all for now to be safe.
  for (const op of opcodes) {
     // Heuristic: if it's a short opcode, it usually has a suffix or is in a specific range.
     // But let's just dump all.
     const fmtName = fmtMap.get(op.fmt) || 'none'
     lines.push(`  OP_${op.name}: { id: "${op.name}", size: ${op.size}, nPop: ${op.nPop}, nPush: ${op.nPush}, format: OpFormat.${fmtName} },`)
  }
  lines.push(`}`)
  lines.push(``)

  // Env Interface
  lines.push(`export interface Env {`)
  lines.push(`  bytecodeVersion: number`)
  lines.push(`  compileOptions: number`)
  lines.push(`  firstAtomId: number`)
  lines.push(`  supportsShortOpcodes: boolean`)
  lines.push(`}`)
  lines.push(``)

  // Env Constant
  lines.push(`export const env = {`)
  lines.push(`  bytecodeVersion: ${bytecodeVersion},`)
  lines.push(`  compileOptions: ${compileOptions},`)
  lines.push(`  firstAtomId: ${firstAtomId},`)
  lines.push(`  supportsShortOpcodes: true,`)
  lines.push(`} as const`)
  lines.push(``)

  writeFileSync(envPath, lines.join('\n'))
  console.log(`Generated ${envPath}`)
}

main().catch(console.error)
