// This file is auto-generated by scripts/getEnv.ts
// Do not edit manually.
// Generated at: 2025-09-24T11:16:24.529Z
export enum CompiledFlags {
  COMPILED_FLAG_NONE = 0,
  COMPILED_FLAG_DUMP = 1 << 0,
  COMPILED_FLAG_BIGNUM = 1 << 1,
}

export class Opcode {
  // TODO
}

export enum OpFormat {
  // TODO
}

export interface OpcodeDefinition {
  name: string;
  format: OpFormat;
  op: number;
}

export const OPCODE_DEFS: Record<string, OpcodeDefinition> = {
  // TODO
};

export const SHORT_OPCODE_DEFS: Record<string, OpcodeDefinition> = {
  // TODO
};

export const env = {
  supportsShortOpcodes: true,
};
